config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  
  delete 'delAll', to: 'tasks#delAll', as: :destroy_all_tasks
  
  get 'sub(/:id)' => 'tasks#sub' , as: :new_sub_task
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    scope :ordered, ->{order(created_at: :desc)}
    has_many :sub_task, foreign_key: "main_task_id", class_name:"Task", dependent: :destroy
    belongs_to :main_task, class_name: "Task", optional: true
    validates :title, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy  ]

  # GET /tasks or /tasks.json
  def index
    if !Task.count.zero?
    @tasks = Task.where(main_task_id: nil).ordered
    end
  end

  def sub
    @main_task = Task.find(params[:id])
    @task = Task.new
    @task.main_task = @main_task
  end

  def delAll
      Task.destroy_all
      redirect_to tasks_path, notice: 'All tasks were successfully deleted.'
  end
  # GET /tasks/1 or /tasks/1.json
  def show
    @sub_tasks = @task.sub_task.ordered
  end

  # GET /tasks/new
  def new
    @task = Task.new(done: false)
  end

  # GET /tasks/1/edit
  def edit
   
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.turbo_stream
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    
    respond_to do |format|
      if @task.update(task_params) 
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
       
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content, content_type: 'application/json'  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :done, :main_task_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoProblem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags  %>

   
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red;flex-basis: 15%;" class = "error">
      <h2> You can't save a task without a title.</h2>
      
    </div>
  <% end %>
<div class="formS">
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :done, style: "display: block" %>
    <%= form.check_box :done, {}, 'true', 'false' %>
  </div>
  
   <%= form.hidden_field :main_task_id %>
  
  
     
  <%= form.submit %>
  
<% end %>
</div>

app/views/tasks/_number-sub.html.erb
<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>
<div id='number-sub'><label for="botao_<%= task.id%>">sub tasks <%=task.sub_task.size%></label></div>

app/views/tasks/_showSub.html.erb
<div class = 'sub-container'>
    <%= check_box_tag "check_#{sub.id}", "true", sub.done, class: 'check' %>
    <label for= "check_<%= sub.id %>" class= "sub-title"><%= sub.title %></label>
    <%= button_to "X", sub, method: :delete, remote: true, 
                data: { turbo_confirm: "Do you really want to delete this sub task?", turbo_frame: "_top" },
                class: 'sub-destroy' %>
    <%= button_to task_path(sub), method: :get, remote: true,class: "sub-show",id: "botao_#{sub.id}",data:{turbo_frame:"_top"} do %>🕮<% end %>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class ="show_task ">
      <div class ='card'>
        <%= check_box_tag "check_#{task.id}", "true", task.done,class: 'check' %>
        <label for= "check_<%= task.id %>" class= "title"><%= task.title %></label>
        <div class='number-sub' id ="number-sub"><label for="botao_<%= task.id%>">sub tasks <%=task.sub_task.size%></label></div>
        <%= button_to task_path(task), method: :get, class: "button-sub",id: "botao_#{task.id}",data:{turbo_frame:"_top"} do %>🕮<% end %>

    </div>
    
    <button class="button-description" >&#128065</button>
    <p class= 'description'><%= task.description %></p>
    
</div>

app/views/tasks/create.turbo_stream.erb
<%=turbo_stream.prepend "sub_tasks", partial:"tasks/showSub", locals:{sub: @task}%>
<%=turbo_stream.prepend "tasks", partial:"tasks/task", locals:{task: @task}%>
<% if @task.main_task.present? %>
    <%=turbo_stream.replace "number-sub", partial: "tasks/number-sub", locals: {task: @task.main_task}%>
<% end %>
<%=turbo_stream.update  Task.new,"" %>

app/views/tasks/edit.html.erb
<%= stylesheet_link_tag "edit", "data-turbo-track": "reload" %>
<%= render "form", task: @task %>

<div class="edit-options">
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "create-task", "data-turbo-track": "reload" %>

<div class= "list_main_task">
  <p style="color: green"><%= notice %></p>
  <div class= "page_title">
    <h1 >TO-DO-LIST</h1>
    <%= link_to "New task", new_task_path,data:{turbo_frame: dom_id(Task.new)} %>
    <%= link_to 'Delete All Tasks', destroy_all_tasks_path, data: { turbo_method: 'delete', turbo_confirm: "do you really want to delete all the tasks?" }  %>
    <div class ="form">
      <%= turbo_frame_tag Task.new%>
    </div>
  </div>
  <%= turbo_frame_tag "task" do%>
  <div id="tasks" class="container">
    <% if !Task.count.zero? %>
        <%= render @tasks%>
      <%end%>
  </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%=turbo_frame_tag @task do%>
  <%= render "form", task: @task %>
<%end%>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "sub-form-turbo", "data-turbo-track": "reload" %>

<p style="color: green"><%= notice %></p>

<div class ='main-task'>
  <%= render @task %>
  <div class='options'>
    <%= link_to "Edit this task", edit_task_path(@task) %> |
    <%= link_to "Back to tasks", tasks_path %>
    <% if @task.main_task.present? %>
      <%= link_to task_path(@task.main_task), method: :get, data: { turbo_frame: "_top" } do %>
        |main task
      <% end %>
    <% end %>
    <%= button_to "Destroy this task", @task, method: :delete %>
  </div>
</div>

<div class ='sub-task'>
  <div class= 'add_sub'>
    <%= button_to new_sub_task_path(id: @task.id),id: @task.id , method: :get, class: "button", data:{turbo_frame:dom_id(Task.new)} do %>&#x1F7C4;<% end %>
    <label for="<%= @task.id%>">Add more</label>
  </div>

  <div class ="sub-form">
    <%= turbo_frame_tag Task.new%>
  </div>
  
  <%=turbo_frame_tag "sub_tasks" do %>
    <div class="sub-task">
      <% @sub_tasks.each do |sub| %>
        <%= render "showSub", sub: sub %>
      <% end %>
    </div>
  <%end%>

 
</div>

<div>

</div>

app/views/tasks/sub.html.erb
<%= stylesheet_link_tag "sub-form-turbo", "data-turbo-track": "reload" %>
 <%= turbo_frame_tag @task do %>
<div class='sub-form'>
    <%= render "form", task: @task %>
    <% end %>
</div>